### ISSUE TITLE
Adding more maintainers?

### ISSUE THREAD

**Issue by jamen** [emerleite/node-gist#7]
@emerleite Hey, I wondering if you were still maintaining this project, or wanted other people to help.

I'd like to use this module for a package I'm creating, but the documentation is obscure, and it looks like this hasn't been updated in 5 years.

If you are, please add me as collaborator to this repository, and on the npm package.  :D

Related #4

**Comment by emerleite** [comment]
Hi @jamen. Feel free to contribute. I'm adding you ;)

**Comment by jamen** [comment]
Awesome, thanks.  :heart:
